---

resources:
  - name: gorrent-git
    type: git
    icon: mdi-github
    source:
      uri: https://github.com/sajfer/gorrent.git

jobs:
  - name: set-self
    public: true
    plan:
      - get: gorrent-git
        trigger: true
      - set_pipeline: gorrent
        file: gorrent-git/pipeline/pipeline.yaml
  - name: test
    public: true
    plan:
      - get: gorrent-git
        trigger: true
        passed: [set-self]
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: golang, tag: "latest" }
          inputs:
            - name: gorrent-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd gorrent-git
                make test

  - name: build
    public: true
    plan:
      - get: gorrent-git
        trigger: true
        passed: [set-self]
      - task: compile
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: golang, tag: "latest" }
          inputs: 
            - name: gorrent-git
          outputs:
            - name: out
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd gorrent-git
                make compile
